# -*- coding: utf-8 -*-
"""Zad2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ua7oxUrOHLY3v7JzbWxtlt_xhTAvWfD2
"""

def pomnoz(a, b):
    return a * b

liczba1 = 5
liczba2 = 3
wynik_mnozenia = pomnoz(liczba1, liczba2)

print(wynik_mnozenia)