# -*- coding: utf-8 -*-
"""Zad3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ua7oxUrOHLY3v7JzbWxtlt_xhTAvWfD2
"""

def czy_parzysta(liczba):
    return liczba % 2 == 0

liczba_do_sprawdzenia = 10
wynik_sprawdzenia = czy_parzysta(liczba_do_sprawdzenia)

if wynik_sprawdzenia:
    print("Liczba parzysta")
else:
    print("Liczba nieparzysta")