# -*- coding: utf-8 -*-
"""Zad3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ua7oxUrOHLY3v7JzbWxtlt_xhTAvWfD2
"""

class Property:
    def __init__(self, area, rooms, price, address):
        self.area = area
        self.rooms = rooms
        self.price = price
        self.address = address

    def __str__(self):
        return f"Property:\nArea: {self.area} sq. m\nRooms: {self.rooms}\nPrice: ${self.price}\nAddress: {self.address}"


class House(Property):
    def __init__(self, area, rooms, price, address, plot):
        super().__init__(area, rooms, price, address)
        self.plot = plot

    def __str__(self):
        return f"{super().__str__()}\nHouse Specific:\nPlot: {self.plot} sq. m"


class Flat(Property):
    def __init__(self, area, rooms, price, address, floor):
        super().__init__(area, rooms, price, address)
        self.floor = floor

    def __str__(self):
        return f"{super().__str__()}\nFlat Specific:\nFloor: {self.floor}"


# Przykładowe użycie
house = House(area=150, rooms=5, price=300000, address="123 Main Street", plot=500)
flat = Flat(area=80, rooms=3, price=150000, address="456 Side Street", floor=2)

# Wyświetlenie obiektów
print(house)
print("\n------------------------\n")
print(flat)