# -*- coding: utf-8 -*-
"""Zad4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ua7oxUrOHLY3v7JzbWxtlt_xhTAvWfD2
"""

def sprawdz_sume(liczba1, liczba2, liczba3):
    suma_dwóch_pierwszych = liczba1 + liczba2
    return suma_dwóch_pierwszych >= liczba3

arg1 = 5
arg2 = 8
arg3 = 12
wynik_sprawdzenia = sprawdz_sume(arg1, arg2, arg3)

print(wynik_sprawdzenia)