# -*- coding: utf-8 -*-
"""Zadania 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13eiKpl--I2fr7sLwCXjIeimx74CDj2IE
"""

def wyswietl_imiona(imiona):
    for imie in imiona:
        print(imie)

lista_imion = ["Anna", "Jan", "Maria", "Piotr", "Katarzyna"]
wyswietl_imiona(lista_imion)

def pomnoz_przez_2_for(lista_liczb):
    wynik = []
    for liczba in lista_liczb:
        wynik.append(liczba * 2)
    return wynik

lista_liczb = [1, 2, 3, 4, 5]
wynik_for = pomnoz_przez_2_for(lista_liczb)
print(wynik_for)

def pomnoz_przez_2_lista_skladana(lista_liczb):
    return [liczba * 2 for liczba in lista_liczb]

lista_liczb = [1, 2, 3, 4, 5]
wynik_lista_skladana = pomnoz_przez_2_lista_skladana(lista_liczb)
print(wynik_lista_skladana)

def wyswietl_parzyste(lista_liczb):
    for liczba in lista_liczb:
        if liczba % 2 == 0:
            print(liczba)

lista_liczb = list(range(1, 11))
wyswietl_parzyste(lista_liczb)

def wyswietl_co_drugi(lista_liczb):
    for i in range(1, len(lista_liczb), 2):
        print(lista_liczb[i])


lista_liczb = list(range(1, 11))
wyswietl_co_drugi(lista_liczb)