# -*- coding: utf-8 -*-
"""Zadanie 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13eiKpl--I2fr7sLwCXjIeimx74CDj2IE
"""

def wyswietl_co_drugi(lista_liczb):
    for i in range(1, len(lista_liczb), 2):
        print(lista_liczb[i])


lista_liczb = list(range(1, 11))
wyswietl_co_drugi(lista_liczb)