# -*- coding: utf-8 -*-
"""Zadania 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13eiKpl--I2fr7sLwCXjIeimx74CDj2IE
"""

def pomnoz_przez_2_for(lista_liczb):
    wynik = []
    for liczba in lista_liczb:
        wynik.append(liczba * 2)
    return wynik

lista_liczb = [1, 2, 3, 4, 5]
wynik_for = pomnoz_przez_2_for(lista_liczb)
print(wynik_for)