# -*- coding: utf-8 -*-
"""Zadania 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13eiKpl--I2fr7sLwCXjIeimx74CDj2IE
"""

def pomnoz_przez_2_lista_skladana(lista_liczb):
    return [liczba * 2 for liczba in lista_liczb]

lista_liczb = [1, 2, 3, 4, 5]
wynik_lista_skladana = pomnoz_przez_2_lista_skladana(lista_liczb)
print(wynik_lista_skladana)