# -*- coding: utf-8 -*-
"""Zadanie 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13eiKpl--I2fr7sLwCXjIeimx74CDj2IE
"""

def wyswietl_parzyste(lista_liczb):
    for liczba in lista_liczb:
        if liczba % 2 == 0:
            print(liczba)

lista_liczb = list(range(1, 11))
wyswietl_parzyste(lista_liczb)